AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Small AWS Lambda Demo Template.
Resources:
  bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
  function:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: build/distributions/lambda-demo-1.0-SNAPSHOT.zip
      Handler: com.hft.example.LambdaHandler
      Runtime: java11
      Description: Java function
      MemorySize: 256
      Timeout: 60
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AWSXrayWriteOnlyAccess
        - AWSLambdaVPCAccessExecutionRole
        - AmazonS3FullAccess
      Tracing: Active
      Events:
        s3Notification:
          Type: S3
          Properties:
            Bucket: !Ref bucket
            Events: s3:ObjectCreated:*